name: Build and Deploy MERN App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./CashFlow_backend

        file: ./CashFlow_backend/DockerFile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cashflow_backend:latest

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./CashFlow_frontend
        file: ./CashFlow_frontend/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cashflow_frontend:latest
        build-args: |
            VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}


  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # - name: injecting github secrets as environment variables
      #   env:
      #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #     MONGODB_URI: ${{ secrets.MONGODB_URI }}
      #     KEY: ${{ secrets.KEY }}
      #     GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      #     PORT: ${{ secrets.PORT }}
      #     VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
      #     MODE: ${{ secrets.MODE }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Deploy Docker containers to EC2
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          KEY: ${{ secrets.KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PORT: ${{ secrets.PORT }}
          VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
          MODE: ${{ secrets.MODE }}
        run: |
            docker compose pull --ignore-pull-failures --parallel
            docker compose up --force-recreate -d